--EJEMPLO PROCEDURE INGRESOS EXTRAS
CREATE OR REPLACE PROCEDURE AUMENTAR_INGRESO_EXTRA(codIng Transaccion.id_tipoTransaccion%TYPE, ratio NUMERIC)
LANGUAGE PLPGSQL	--DEBEMOS COLOCAR EL LENGUAJE
AS $$ --SUSTITUTO DE LAS COMILLAS
BEGIN
	--PODEMOS EJECUTAR SENTENCIAS SQL Y ACTUALIZAR DATOS: UPDATE, DELETE
	UPDATE Transaccion SET monto = (1 + ratio) * monto
	WHERE id_tipoTransaccion = codIng;
END; $$--SUSTITUTO DE LAS COMILLAS

--PRUEBAS (BLOQUE ANOMIMO)
DO $$
BEGIN
	CALL AUMENTAR_INGRESO_EXTRA(3, 0.1); --LLAMADO A PROCEDURE
END; $$

--COMPROBACION DE RESULTADOS
select * from Transaccion where id_tipoTransaccion = 3;


--EJEMPLO PROCEDURE EGRESOS EXTRAS
CREATE OR REPLACE PROCEDURE AUMENTAR_EGRESO_EXTRA(codEg Transaccion.id_tipoTransaccion%TYPE, ratio NUMERIC)
LANGUAGE PLPGSQL	--DEBEMOS COLOCAR EL LENGUAJE
AS $$ --SUSTITUTO DE LAS COMILLAS
BEGIN
	--PODEMOS EJECUTAR SENTENCIAS SQL Y ACTUALIZAR DATOS: UPDATE, DELETE
	UPDATE Transaccion SET monto = (1 + ratio) * monto
	WHERE id_tipoTransaccion = codEg;
END; $$--SUSTITUTO DE LAS COMILLAS

--PRUEBAS (BLOQUE ANOMIMO)
DO $$
BEGIN
	CALL AUMENTAR_EGRESO_EXTRA(4, 0.1); --LLAMADO A PROCEDURE
END; $$

--COMPROBACION DE RESULTADOS
select * from Transaccion where id_tipoTransaccion = 4;